(function(){
	'use strict';

	angular
	.module('bzSaleContact')
	.constant('LEANRNER_LEVEL_LIST', [
		{name: "A1",	value: "A1"},
		{name: "A2",	value: "A2"},
		{name: "B1",	value: "B1"},
		{name: "B2",	value: "B2"},
		{name: "C1",	value: "C1"},
		{name: "C2",	value: "C2"},
		])
	.constant('CAREER_LIST', [
		{name: "Hành chính văn phòng", 		value: "Hành chính văn phòng"},
		{name: "Nông lâm nghiệp", 			value: "Nông lâm nghiệp"},
		{name: "Hàng không/Du lịch", 		value: "Hàng không/Du lịch"},
		{name: "Kiến trúc/Xây dựng", 		value: "Kiến trúc/Xây dựng"},
		{name: "Nghệ thuật/Thiết kế", 		value: "Nghệ thuật/Thiết kế"},
		{name: "Ngân hàng", 				value: "Ngân hàng"},
		{name: "Kinh doanh", 				value: "Kinh doanh"},
		{name: "Hóa học/Sinh học", 			value: "Hóa học/Sinh học"},
		{name: "Truyền thông", 				value: "Truyền thông"},
		{name: "Dịch vụ khách hàng", 		value: "Dịch vụ khách hàng"},
		{name: "Giáo dục/Đào tạo", 			value: "Giáo dục/Đào tạo"},
		{name: "Kỹ thuật/Công nghệ", 		value: "Kỹ thuật/Công nghệ"},
		{name: "Môi trường", 				value: "Môi trường"},
		{name: "Xuất nhập khẩu", 			value: "Xuất nhập khẩu"},
		{name: "Tài chính", 				value: "Tài chính"},
		{name: "Ẩm thực", 					value: "Ẩm thực"},
		{name: "Vận tải", 					value: "Vận tải"},
		{name: "Địa chất", 					value: "Địa chất"},
		{name: "Lịch sử", 					value: "Lịch sử"},
		{name: "Khách sạn", 				value: "Khách sạn"},
		{name: "Nhân sự", 					value: "Nhân sự"},
		{name: "Công nghệ thông tin", 		value: "Công nghệ thông tin"},
		{name: "Kế toán/Kiểm toán", 		value: "Kế toán/Kiểm toán"},
		{name: "Marketing", 				value: "Marketing"},
		{name: "Y tế/chăm sóc sức khỏe", 	value: "Y tế/chăm sóc sức khỏe"},
		{name: "Luật", 						value: "Luật"},
		{name: "Vật lý", 					value: "Vật lý"},
		{name: "Bán hàng", 					value: "Bán hàng"},
		{name: "Học sinh", 					value: "Học sinh"},
		{name: "Sinh viên", 				value: "Sinh viên"},
		])
	.constant('BANK_LIST', [
		{name: 'Vietcombank - Ngoại thương Việt Nam', 		value: 'VCB'},
		{name: 'Vietinbank - Công Thương Việt Nam', 		value: 'CTG'},
		{name: 'BIDV - BID - Đầu tư và Phát triển Việt Nam', value: 'BIDV'},
		{name: 'Agribank - Ngân hàng Nông nghiệp và Phát triển Nông thôn VN', value: 'Agribank'},
		{name: 'Techcombank - Kỹ Thương Việt Nam', 			value: 'Techcombank'},
		{name: 'ACB - Ngân hàng Á Châu', 					value: 'ACB'},
		{name: 'Sacombank - Sài Gòn Thương Tín', 			value: 'STB'},
		{name: 'Ngân hàng Chính sách Xã hội Việt Nam', 		value: 'VBSP'},
		{name: 'Ngân hàng Phát triển Việt Nam', 			value: 'VDB'},
		{name: 'Construction Bank - Ngân hàng Xây dựng', 	value: 'CB'},
		{name: 'Ocean Bank - Ngân hàng Đại Dương', 			value: 'Oceanbank'},
		{name: 'Global Petro Bank - Ngân hàng Dầu Khí Toàn Cầu', value: 'GPBank'},
		{name: 'Tien Phong Bank - Ngân hàng Tiên Phong', 	value: 'TPBank'},
		{name: 'DongA Bank - Ngân hàng Đông Á', 			value: 'DAF'},
		{name: 'SeABank - Ngân hàng Đông Nam Á', 			value: 'SeABank'},
		{name: 'An Binh Bank - Ngân hàng An Bình', 			value: 'ABBANK'},
		{name: 'Bac A Bank - Ngân hàng Bắc Á', 				value: 'BacABank'},
		{name: 'Viet Capital Bank - Ngân hàng Bản Việt', 	value: 'VietCapitalBank'},
		{name: 'Maritime Bank - Hàng Hải Việt Nam', 		value: 'MSB'},
		{name: 'KienLongBank - Kiên Long', 					value: 'KienLongBank'},
		{name: 'Nam A Bank - Nam Á', 						value: 'Nam A Bank'},
		{name: 'NCB - Quốc Dân', 							value: 'NCB'},
		{name: 'VPBank - Việt Nam Thịnh Vượng', 			value: 'VPBank'},
		{name: 'HDBank - Phát triển Thành phố Hồ Chí Minh', value: 'HDBank'},
		{name: 'OCB - Phương Đông', 						value: 'OCB'},
		{name: 'Military Bank - Quân đội', 					value: 'MBB'},
		{name: 'PVcom Bank - Đại chúng', 					value: 'PVcom Bank'},
		{name: 'VIBBank - Quốc tế', 						value: 'VIB'},
		{name: 'SCB - Sài Gòn', 							value: 'SCB'},
		{name: 'Saigonbank - Sài Gòn Công Thương', 			value: 'SGB'},
		{name: 'SHB - Sài Gòn-Hà Nội', 						value: 'SHB'},
		{name: 'VietABank - Việt Á', 						value: 'VAB'},
		{name: 'BaoVietBank - Bảo Việt', 					value: 'BVB'},
		{name: 'VietBank - Việt Nam Thương Tín', 			value: 'VietBank'},
		{name: 'PG Bank - Xăng dầu Petrolimex', 			value: 'PG Bank'},
		{name: 'Eximbank - Xuất Nhập khẩu Việt Nam', 		value: 'EIB'},
		{name: 'LienVietPostBank - Bưu điện Liên Việt', 	value: 'LPB'},
		{name: 'Ngân hàng TNHH một thành viên ANZ (Việt Nam)', value: 'Australia And Newzealand Bank'},
		{name: 'Deutsche Bank Việt Nam', 					value: 'ADeutsche Bank AG, Vietnam'},
		{name: 'Ngân hàng Citibank Việt Nam', 				value: 'Citibank'},
		{name: 'HSBC - Ngân hàng TNHH một thành viên HSBC (Việt Nam)', value: 'HSBC'},
		{name: 'Standard Chartered (Việt Nam)', 			value: 'Standard Chartered'},
		{name: 'Ngân hàng TNHH MTV Shinhan Việt Nam', 		value: 'Shinhan Vietnam Bank Limited - SHBVN'},
		{name: 'Ngân hàng Hong Leong Việt Nam', 			value: 'Hong Leong Bank Vietnam Limited - HLBVN'},
		{name: 'BIDC - Ngân hàng Đầu tư và Phát triển Campuchia', value: 'BIDC'},
		{name: 'PBBVN - Public Bank Việt Nam', 				value: 'PBBVN'},
		{name: 'UOB - Ngân hàng United Overseas Bank tại Việt Nam', value: 'UOB'},
		{name: 'IVB - Ngân hàng TNHH Indovina', 			value: 'IVB'},
		{name: 'VRB - Ngân hàng Việt - Nga', 				value: 'VRB'},
		{name: 'VSB - Ngân hàng Việt - Thái', 				value: 'VSB'},
		])
	.constant('LEVEL_LIST', [
		{value: '1_BGLS', 		name: "Bận gọi lại sau", 			group: 'Level 1'},
		{value: '1_KLLD', 		name: "Không liên lạc được", 		group: 'Level 1'},
		{value: '1_KNM', 		name: "Không nhấc máy.", 			group: 'Level 1'},
		{value: '1_SS', 		name: "Sai số.", 					group: 'Level 1'},
		{value: '1_KDDT', 		name: "Không đúng đối tượng.",		group: 'Level 1'},

		{value: '2_DDTLLD', 	name: "Đúng đối tượng, liên lạc được", 					group: 'Level 2'},
		{value: '2_DDTLLDCCNN', name: "Đúng đối tượng, liên lạc đc, nhưng chưa có nhu cầu tại thời điểm hiện tại", 	group: 'Level 2'},
		{value: '2_QT', 		name: "Quan tâm nhưng cần thời gian tham khảo thêm", 	group: 'Level 2'},
		{value: '2_KQT', 		name: "Không quan tâm từ chối tiếp nhận thông tin", 	group: 'Level 2'},

		{value: '3_DYT', 		name: "Đồng ý test", 											group: 'Level 3'},
		{value: '3_QTVCL', 		name: "Quan tâm và có lịch hẹn cụ thể trực tiếp tại VP", 		group: 'Level 3'},
		{value: '3_QTVCLKCT', 	name: "Quan tâm và có lịch hẹn nhưng không cụ thể", 			group: 'Level 3'},
		{value: '3_QTVCLCT', 	name: "Quan tâm và có lịch hẹn cụ thể trực tiếp tại văn phòng", group: 'Level 3'},
		{value: '3_CHNKD', 		name: "Có hẹn nhưng không đến hoặc chưa làm test", 				group: 'Level 3'},

		{value: '4_CBDD', 		name: "Contact biết đầy đủ thông tin",				group: 'Level 4'},
		{value: '4_CDLVP', 		name: "Contact đã lên văn phòng",					group: 'Level 4'},
		{value: '4_CDHT', 		name: "Contact đã hoàn thiện 1 trong 2 bài test",	group: 'Level 4'},

		{value: '5_CDHTT', 		name: "Contact đã hoàn thành bài test phỏng vấn và bài kiểm tra",	group: 'Level 5'},

		{value: '6_DDNLTCB', 	name: "Đồng ý nhận lộ trình từ cơ bản nhất",	group: 'Level 6'},
		{value: '6_DNLTHH', 	name: "Đã nhận lộ trình học tập",				group: 'Level 6'},
		{value: '6_CHCK', 		name: "Có hẹn chuyển khoản",					group: 'Level 6'},

		{value: '7_DDMP', 		name: "Đã đóng một phần học phí",				group: 'Level 7'},

		{value: '8_DNH', 		name: "Đã nhập học",							group: 'Level 8'},
		])
	.constant('CARESTATUS_LIST', [
		{value: '1_UDF', 		name: "Chưa xác định"},
		{value: '2_TTCS', 		name: "Tiếp tục chăm sóc"},
		{value: '3_CSSMTG', 	name: "Chăm sóc sau một thời gian nữa"},
		{value: '4_KNGN', 		name: "Không nên gọi nữa"},
		])
	.constant('QUALITYCALL_LIST', [
		{value: '1_KSS', 		name: "Không sẵn sàng tiếp nhận cuộc gọi"},
		{value: '2_DKNKN', 		name: "Đăng ký nhưng không nhớ"},
		{value: '3_KHHTT', 		name: "Không hiểu học trực tuyến là gì"},
		{value: '4_DLSV', 		name: "Đang là sinh viên"},
		{value: '5_DKCC', 		name: "Đăng ký cho con"},
		{value: '6_NLDCCC', 	name: "Nghĩ là được cấp chứng chỉ"},
		])
	.constant('SOURCE_LIST', [
		{value: 'MTO', 		name: "Marketing online"},
		{value: 'CTC', 		name: "Contact collecter"},
		{value: 'CTH', 		name: "Contact hotline"},
		{value: 'CTT', 		name: "Contact tư vấn tuyển sinh thu thập, học viên khác giới thiệu"},
		]);
})();
